apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kepler.name" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      {{- include "kepler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kepler.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: "None"
      dnsConfig:
        nameservers: ["127.0.0.53"]
      serviceAccountName: {{ .Values.serviceAccount.name }}
      initContainers:
        - name: install-kernel-headers
          image: ubuntu:22.04
          command: ['/bin/sh']
          args:
            - -c
            - |
              /usr/bin/apt update
              /usr/bin/apt install -y linux-headers-generic
          securityContext:
            privileged: true
      containers:
      - name: kepler-exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
        securityContext:
          privileged: true
        command:
        - /usr/bin/kepler
        - -address
        - 0.0.0.0:{{ .Values.service.port }}
        - -enable-gpu=true
        - -enable-cgroup-id=true
        - -v=1
        ports:
        - containerPort: {{ .Values.service.port }}
          hostPort: {{ .Values.service.port }}
          name: http
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: {{ .Values.service.port }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /sys
          name: tracing
        - mountPath: /proc
          name: proc
        - mountPath: /usr/src
          name: usr-src
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CPU_ARCH_OVERRIDE
          value:
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: tracing
        hostPath:
          path: /sys
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: usr-src
        hostPath:
          path: /usr/src
          type: Directory
